### ISSUE TITLE
NullReferenceException in Dispose Method

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.Data.MySql#1]
Tried to run Entity Framework Migration, got the following:

    Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
    at Pomelo.Data.MySql.Driver.Dispose(Boolean disposing)
    at Pomelo.Data.MySql.Driver.Finalize()

**Comment by Kagamine** [comment]
![image](https://cloud.githubusercontent.com/assets/2216750/16874297/0a55a0a2-4acb-11e6-958c-bf70090ef6fc.png)

I've just made a test, it seems works fine, can you provide me your dbcontext and your models?

Did you use the json field type in your model?

**Comment by Kagamine** [comment]
We have made some changes today, you can have a try to remove cached nuget packages where located in `C:\Users\YOURNAME\.nuget\packages`. If this issue still occur after removing `Pomelo.Data.MySql` and `Pomelo.EntityFrameworkCore.MySql`, please continue comment here.

**Comment by caleblloyd** [comment]
Yes, I've updated from NuGet. This is a new bug, I think it was introduced in this commit: 30c9dc2a80cbf755567800ae97dbd41c33f2531f

**Comment by Kagamine** [comment]
Can you give me your dbcontext & models, I cannot reproduce now.

**Comment by caleblloyd** [comment]
I just forked, I'll try to find the fix real quick.  If I can't get it, I'll upload my dbcontext and models, give me 30 mins.

**Comment by Kagamine** [comment]
:smile:

**Comment by caleblloyd** [comment]
How is Multiple Readers on the same connection supposed to work in https://github.com/PomeloFoundation/Pomelo.Data.MySql/commit/30c9dc2a80cbf755567800ae97dbd41c33f2531f?

Can't MySQL only do a single reader per connection because the ResultSet is tracked on the Connection basis?

**Comment by Kagamine** [comment]
I am not sure the commit solved MARS issue, but just makes .Include and .ThenInclude work.

**Comment by caleblloyd** [comment]
Found it!  Pull request opened.
