### ISSUE TITLE
ExecuteReaderAsync blocking

### ISSUE THREAD

**Issue by dandago** [PomeloFoundation/Pomelo.Data.MySql#10]
The implementation of `ExecuteReaderAsync` [uses a blocking method call and is wrapped in a `TaskCompletionSource`](https://github.com/PomeloFoundation/Pomelo.Data.MySql/blob/aaf215852d594d09cf6518e50392b596b46a9f18/src/Pomelo.Data.MySql/MySqlHelper.cs#L727).

This has the effect of [blocking GUI applications even when they use async calls throughout the stack](https://stackoverflow.com/q/44898624/983064).

**Comment by Kagamine** [comment]
Use https://www.nuget.org/packages/MySqlConnector/
