### ISSUE TITLE
Cannot use Library for Store Apps

### ISSUE THREAD

**Issue by QuickScoP3s** [PomeloFoundation/Pomelo.Data.MySql#13]
### The issue
When using the app in both debug and release mode, no problems arise
So I submitted the app to the store, but it's not allowed:

Error Found: The supported APIs test detected the following errors:
API CreateFileW in kernel32.dll is not supported for this application type. Pomelo.Data.MySql.dll calls this API.
API MapViewOfFile in kernel32.dll is not supported for this application type. Pomelo.Data.MySql.dll calls this API.
API OpenFileMappingW in kernel32.dll is not supported for this application type. Pomelo.Data.MySql.dll calls this API.
API AcquireCredentialsHandleW in secur32.dll is not supported for this application type. Pomelo.Data.MySql.dll calls this API.
API CompleteAuthToken in secur32.dll is not supported for this application type. Pomelo.Data.MySql.dll calls this API.
API DeleteSecurityContext in secur32.dll is not supported for this application type. Pomelo.Data.MySql.dll calls this API.
API FreeCredentialsHandle in secur32.dll is not supported for this application type. Pomelo.Data.MySql.dll calls this API.
API InitializeSecurityContextW in secur32.dll is not supported for this application type. Pomelo.Data.MySql.dll calls this API.
API QueryContextAttributesW in secur32.dll is not supported for this application type. Pomelo.Data.MySql.dll calls this API.
API WaitForSingleObject in coredll.dll is not supported for this application type. Pomelo.Data.MySql.dll calls this API.

**Comment by Kagamine** [comment]
This lib is obsoleted, please use github.com/mysql-net/mysqlconnector
